### ISSUE TITLE
Disabling Jolly - Pin Control

### ISSUE THREAD

**Issue by Hikari1026** [tech-jollydev/jolly-arduino-platform#1]
Hi, I'm tinkering and having fun with the Jolly dev board. I've noticed that whenever the board is connected to internet (I've tested only via Wifi though) opens by default an 80 port with the Jolly Pin Control page. Even though this function is nice, I would like to disable it.

I've been looking for the point where this function is called inside the core but had no luck (no references for the html page either), is there any way to disable this?
Thank you in advance.

**Comment by tech-jollydev** [comment]
Hi there!
Currently there is no function available to disable the default server on port 80. It is instantiated by the WiFi module, the esp8285, and the code for this module is currently available only in binary form. We are working to add some functions on the WiFi library to disable the default server, so that this feature will be available in the next release.
Thank you for reporting!

**Comment by tech-jollydev** [comment]
Version 1.0.1 has been released. With this version is possible to call disableWebPanel function from WiFi library to disable the default server on port 80. Note that in order to work the default firmware on ESP8285 needs to be reloaded. Follow the instructions on README for more information about this procedure.
